# Generated by Django 4.2.7 on 2023-11-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_member_presents_gift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gift',
        ),
    ]
