# Generated by Django 4.2.7 on 2023-11-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_gift'),
        ('presents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.family'),
            preserve_default=False,
        ),
    ]
