# Generated by Django 4.2.7 on 2023-11-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_gift'),
        ('presents', '0002_gift_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presents.gift')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.member')),
            ],
        ),
    ]
