# Generated by Django 4.2.7 on 2023-11-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presents', '0003_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='family',
        ),
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.CharField(choices=[('PRICE1', 'Moins de 40 €'), ('PRICE2', 'Entre 40 et 100 €'), ('PRICE3', 'Plus de 100€')], max_length=20),
        ),
    ]
